name: Build Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: ["main","php-*"]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]


permissions:
  contents: read
  id-token: write
  packages: write
  

jobs:   
  build-docker-web-app :
    uses: ./.github/workflows/common-build-docker.yml
    with:
      context: .
      dockerfile: Dockerfile
      image-name: ${{ github.repository_owner	}}/opensignature-webapp

  build-docker-corn :
    uses: ./.github/workflows/common-build-docker.yml
    with:
      context: .
      dockerfile: Dockerfile.cron
      image-name: ${{ github.repository_owner	}}/opensignature-cron
   